### ISSUE TITLE
Tab close button has empty tooltip...?

### ISSUE THREAD

**Issue by dominichayesferen** [angelbruni/Geckium#113]
That Linux Dude Dominic Hayes thatlinuxdude
 — 22/05/2024 21:37

yeah, it just... has an empty tooltip??

**Comment by angelbruni** [comment]
I don't think this was caused by Geckium, and even if it was, the code for tabs changed.

**Comment by dominichayesferen** [comment]
It's ironic - I actually encountered this again yesterday but forgor to mention it

**Comment by angelbruni** [comment]
> It's ironic - I actually encountered this again yesterday just as randomly but forgor to mention it

Really doubt we cause this at this point, considering we don't replace the entire tab code anymore, nor do we move the close element around.
Blame Mozilla momento.
