### ISSUE TITLE
Link drag indicator arrow is broken

### ISSUE THREAD

**Issue by dominichayesferen** [angelbruni/Geckium#200]
KAWKNAKNWKA kwanvini
 — 18/10/2024 17:35

![image](https://github.com/user-attachments/assets/33f9a9e7-b436-4c4f-8967-dc1000fdbbd5)

**Comment by angelbruni** [comment]
Fixed in commit https://github.com/angelbruni/Geckium/commit/ac71700ff264b1fdcffc26a96dfed7f378cde68e
