### ISSUE TITLE
Commit "Move infobars to above bookmarks bar when floating" broke the infobar

### ISSUE THREAD

**Issue by dominichayesferen** [angelbruni/Geckium#205]
Windows 10 Firefox 115

Before commit:

![image](https://github.com/user-attachments/assets/da51afe5-3843-4898-803f-08852b8ab859)

After commit:

![image](https://github.com/user-attachments/assets/33d4639a-98c0-4e9e-baee-6f96bb56deab)

**Comment by angelbruni** [comment]
Fixed in commits https://github.com/angelbruni/Geckium/commit/ca0eb7e9facec9368985d32af2239c5e68bf960c and https://github.com/angelbruni/Geckium/commit/1553dd1ac260edca90ba8fd8b2376ecdffdd1fde.
