### ISSUE TITLE
Implement Dino game (chrome://dino) into Geckium

### ISSUE THREAD

**Issue by ImSwordQueen** [angelbruni/Geckium#206]
(Originally posted by inkatail on Discord)

Would chrome://dino on some error pages be possible to implement?
~~Also Idk which version of chrome added it~~

According to Google, it was released in Chrome 38

**Comment by SoftwareType** [comment]
I have heard of some accurate clones, but they're in HTML rather than just CSS

**Comment by aubymori** [comment]
> I have heard of some accurate clones, but they're in HTML rather than just CSS

This isn't an issue. Geckium already extensively uses custom HTML documents.
