### ISSUE TITLE
[Chrome 4-5] Incognito new tab page isn't adjusted for dark mode

### ISSUE THREAD

**Issue by forkiesassds** [angelbruni/Geckium#208]
Public beta 1, on Arch Linux running Firefox 131

![Screenshot_20241021_074133](https://github.com/user-attachments/assets/c8da2e85-f1c5-400e-9fde-51a6a50fe5fd)

Also nitpick, the X button on tabs doesn't adjust for dark mode either, nor the buttons on the toolbar as they appear to be way too bright for typical dark mode buttons.

**Comment by angelbruni** [comment]
Fixed in commit https://github.com/angelbruni/Geckium/commit/55d84a9e2f846e61923b12ca15aa0ab1c894bace. Thanks.
