### ISSUE TITLE
themes..

### ISSUE THREAD

**Issue by fishcelery4894** [angelbruni/Geckium#213]
so i got two (non default) crx files
![image](https://github.com/user-attachments/assets/5b6b00fe-265b-4821-80a1-114811a9e6a1)

but they arent listed
![image](https://github.com/user-attachments/assets/7c0d856e-f241-4a9d-81b5-f1a58c25cfab)

am i dumb or am i doing something wrong
sorry if this issue is a silly one

**Comment by angelbruni** [comment]
Update your Firefox to latest release if you don't mind aero, if you do then update 115ESR to 115.16.1ESR or r3dfox (128ESR).

**Comment by dominichayesferen** [comment]
State your version of Firefox

ALT key -> Help -> About

**Comment by fishcelery4894** [comment]
![image](https://github.com/user-attachments/assets/5fac608d-8dab-4c3a-ae24-9584ec7b3e3a)

**Comment by dominichayesferen** [comment]
> ![image](https://private-user-images.githubusercontent.com/159673412/378593813-5fac608d-8dab-4c3a-ae24-9584ec7b3e3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NDQxNDQsIm5iZiI6MTcyOTU0Mzg0NCwicGF0aCI6Ii8xNTk2NzM0MTIvMzc4NTkzODEzLTVmYWM2MDhkLThkYWItNGMzYS1hZTI0LTk1ODRlYzdiM2UzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQyMDUwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGU3NWExZjFhNDgwODY4MThjYTlhMGI0ZTQ2MDMwYTc0MmE2YTQyNzhmYWM0N2JlYmMzZGRhN2EzMTk0ZDZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1ulCO5yTCvBYu_IjNPi73n36ZWDT8cVJ6hVLoA8ktKY) it might also be the name?

Huh, you're on the latest 115...  what.

**Comment by fishcelery4894** [comment]
im on windows 7 if that means anything

**Comment by dominichayesferen** [comment]
Check your hamburger menu - is it advertising a new build of Geckium?

**Comment by fishcelery4894** [comment]
im on the latest geckium

**Comment by dominichayesferen** [comment]
Please do the following:

1. Open Inspect Element (CTRL+SHIFT+I)
2. In Inspect Element, click ... and enter Settings
3. Find and enable browser toolbox and remote debugging
4. Enable the menubar
5. Go to Tools -> Browser Tools -> Browser Toolbox
6. Confirm connection, then in the new window go to Console
7. Click the trash to clear the log
8. In Firefox, refresh Geckium Settings
9. Copy and paste all the logs, in the new window, below

**Comment by fishcelery4894** [comment]
cant find enable menubar

**Comment by angelbruni** [comment]
Right click the titlebar or press ALT

**Comment by fishcelery4894** [comment]
cant find browser toolbox..

**Comment by dominichayesferen** [comment]
Browser Toolbox only appears if you have enabled it and remote debugging in Inspect Element settings

**Comment by angelbruni** [comment]
![image](https://github.com/user-attachments/assets/fdb53f9c-b579-4b94-9d73-2349837fbcdf)
In inspect element, you need to enable those first, then try to find browser toolbox in menubar -> Tools -> Browser Tools -> Browser Toolbox

**Comment by fishcelery4894** [comment]
oh thx

**Comment by fishcelery4894** [comment]
how do i refresh geckium settings

**Comment by dominichayesferen** [comment]
press Refresh if a page, otherwise if a window just reopen it

**Comment by fishcelery4894** [comment]
ok i closed firefox and im back, now what

**Comment by angelbruni** [comment]
> Please do the following:
> 
>     1. Open Inspect Element (CTRL+SHIFT+I)
> 
>     2. In Inspect Element, click ... and enter Settings
> 
>     3. Find and enable browser toolbox and remote debugging
> 
>     4. Enable the menubar
> 
>     5. Go to Tools -> Browser Tools -> Browser Toolbox
> 
>     6. Confirm connection, then in the new window go to Console
> 
>     7. Click the trash to clear the log
> 
>     8. In Firefox, refresh Geckium Settings
> 
>     9. Copy and paste all the logs, in the new window, below

You only needed to reopen Geckium Settings.
Anyways, again, open browser toolbox and do steps 6 through 9 ^

**Comment by fishcelery4894** [comment]
uhh, which logs
i checked and the themes still arent there, maybe its the crx files that are broken

**Comment by dominichayesferen** [comment]
the Console will spew text out upon loading Settings

**Comment by dominichayesferen** [comment]
that text is the logs.

**Comment by fishcelery4894** [comment]
where in inspect also what new window?
(im sorry im dumb)

**Comment by dominichayesferen** [comment]
are you in the Discord server?

**Comment by fishcelery4894** [comment]
nope

**Comment by fishcelery4894** [comment]
ill join if i need to

**Comment by angelbruni** [comment]
![image](https://github.com/user-attachments/assets/db21a1f3-4072-47da-bc69-c6b35da75e44)

**Comment by dominichayesferen** [comment]
> where in inspect also what new window? (im sorry im dumb)

![image](https://github.com/user-attachments/assets/8b725086-1410-48ae-ae9c-524e9d986536)

(... -> Settings)

**Comment by dominichayesferen** [comment]
new window referring to the window that appears upon selecting Browser Toolbox from Browser Tool- oh bruni said it

**Comment by fishcelery4894** [comment]
oh

**Comment by fishcelery4894** [comment]
i think i did it right, i cleared toolbox with geck settings open
closes geck settings, toolbox still open
reopened geck settings and copied what was in the toolbox

**Comment by angelbruni** [comment]
1 - Open browser toolbox
2 - Go to console
3 - Clear logs
4 - Open Geckium Settings
5 - Copy the new logs
6 - Send here

**Comment by angelbruni** [comment]
Sorry if we are not clear enough

**Comment by dominichayesferen** [comment]
> i think i did it right, i cleared toolbox with geck settings open closed geck settings, toolbox still open reopened geck settings and copied what was in the toolbox

it would be cleaner if you close Settings, THEN clear, but yeah copy everything in the box and paste it here.

**Comment by fishcelery4894** [comment]
lagged a bit

**Comment by fishcelery4894** [comment]
oh

**Comment by fishcelery4894** [comment]
heres the logs i got

CRX getThemes: Looking for themes in C:/Users/Fishy/AppData/Roaming/Mozilla/Firefox/Profiles/sl42x965.default-esr-1711493313018/chrThemes... [Geckium_themesChr.uc.js:46:25](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
Object { name: "Linux Pre-Alpha Titlebar", description: "Removes the Google logo from the Windows titlebar style, emulating how titlebars looked on Pre-Alpha builds of Chromium on Linux. Requires the titlebar style being set to Windows to take effect, and overrides the logo on other titlebar styles experiment.", styleints: (2) […] }
 false [chrFlags.js:9:11](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
Object { name: "Linux Titlebar Buttons Prototype 1", description: "Replaces the close button with a picture of Glen Murphy's head, as seen in Chromium 3.0 Alpha on Linux, now with its passive aggressive purpose satisfied. Glen designed the scrapped Linux (Alpha) titlebar buttons design for Chromium, and his face requires the titlebar style being set to Windows to take effect.", styleints: (2) […] }
 false [chrFlags.js:9:11](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
Object { name: "Google logo on other platforms' titlebars", description: "Show the Google logo in other platforms' titlebar styles, rather than only on the Windows titlebar styles. Requires Google Chrome branding to take effect.", styleints: (3) […] }
 false [chrFlags.js:9:11](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
Object { name: "Enable search button in Omnibox", description: "Places a search button in the Omnibox.", styleints: (1) […], values: {…} }
 true [chrFlags.js:9:11](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
0 Default [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
1 Disabled [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
2 Enabled on search result pages [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
3 Enabled on search result pages or when input in progress [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
4 Enabled on all pages [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
Object { type: "ntp", name: "Enable large icons on the New Tab", description: "Enable the experimental New Tab page using large icons.", styleints: (1) […] }
 false [chrFlags.js:9:11](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
Object { name: "Omnibox UI Vertical Layout", description: "Displays Omnibox sugestions in 2 lines - title over origin.", styleints: (1) […] }
 false [chrFlags.js:9:11](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
Object { name: "Omnibox UI Vertical Margin", description: "Changes the vertical margin in the Omnibox UI.", styleints: (1) […], values: {…} }
 true [chrFlags.js:9:11](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
0 Default [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
1 Enabled [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
2 Enabled 4px vertical margin [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
3 Enabled 6px vertical margin [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
4 Enabled 8px vertical margin [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
5 Enabled 10px vertical margin [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
6 Enabled 12px vertical margin [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
7 Enabled 14px vertical margin [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
8 Disabled [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
Object { name: "Omnibox UI Swap Title and URL", description: "In the omnibox dropdown, shows titles before URLs when both are available.", styleints: (1) […], values: {…} }
 true [chrFlags.js:9:11](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
0 Default [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
1 Enabled [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
2 Disabled [chrFlags.js:54:13](chrome://userchrome/content/windows/gsettings/scripts/chrFlags.js)
Uncaught TypeError: page is null
    skipToPage chrome://userchrome/content/frameworks/GeckiumMaterial/scripts/pages.js:18
    <anonymous> chrome://userchrome/content/frameworks/GeckiumMaterial/zoo/script.js:3
    EventListener.handleEvent* chrome://userchrome/content/frameworks/GeckiumMaterial/zoo/script.js:1
[pages.js:18:20](chrome://userchrome/content/frameworks/GeckiumMaterial/scripts/pages.js)
Uncaught TypeError: selector.setValue is not a function
    loadSelectorSetting chrome://userchrome/content/windows/gsettings/scripts/settingsLoader.js:14
    loadSelectorSetting chrome://userchrome/content/windows/gsettings/scripts/settingsLoader.js:5
    setTimeout handler*loadSelectorSetting chrome://userchrome/content/windows/gsettings/scripts/settingsLoader.js:4
    EventListener.handleEvent* chrome://userchrome/content/windows/gsettings/scripts/settingsLoader.js:39
[settingsLoader.js:14:13](chrome://userchrome/content/windows/gsettings/scripts/settingsLoader.js)
CRX getThemes: Got response from manifest:  
Response { type: "basic", url: "jar:file:///C:/Users/Fishy/AppData/Roaming/Mozilla/Firefox/Profiles/sl42x965.default-esr-1711493313018/chrThemes/Geckium_Tan.crx!/manifest.json", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers(2), body: ReadableStream, bodyUsed: false, hasCacheInfoChannel: false }
[Geckium_themesChr.uc.js:54:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got valid theme manifest:  
Object { name: "Geckium-tan", version: "1.0", description: "A Geckium-tan theme!", manifest_version: 3, theme: {…} }
[Geckium_themesChr.uc.js:60:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got theme name and description: Geckium-tan: A Geckium-tan theme! [Geckium_themesChr.uc.js:96:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got theme banner: images/theme_ntp_background.png, 0,0,0 [Geckium_themesChr.uc.js:125:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got theme icon: undefined [Geckium_themesChr.uc.js:143:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got browser origin: chrome [Geckium_themesChr.uc.js:154:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Added theme info to grid!  
Object { file: "Geckium_Tan.crx", browser: "chrome", name: "Geckium-tan", description: "A Geckium-tan theme!", version: "1.0", banner: "images/theme_ntp_background.png", color: (3) […], icon: undefined }
[Geckium_themesChr.uc.js:167:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Attempting to read the manifest of Geckium_Tan_Non_Aero.crx [Geckium_themesChr.uc.js:51:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got response from manifest:  
Response { type: "basic", url: "jar:file:///C:/Users/Fishy/AppData/Roaming/Mozilla/Firefox/Profiles/sl42x965.default-esr-1711493313018/chrThemes/Geckium_Tan_Non_Aero.crx!/manifest.json", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers(2), body: ReadableStream, bodyUsed: false, hasCacheInfoChannel: false }
[Geckium_themesChr.uc.js:54:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got valid theme manifest:  
Object { name: "Geckium-tan (Non-aero)", version: "1.0", description: "A non-aero version of the Geckium-tan theme!", manifest_version: 3, theme: {…} }
[Geckium_themesChr.uc.js:60:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got theme name and description: Geckium-tan (Non-aero): A non-aero version of the Geckium-tan theme! [Geckium_themesChr.uc.js:96:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got theme banner: images/theme_ntp_background.png, 0,0,0 [Geckium_themesChr.uc.js:125:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got theme icon: undefined [Geckium_themesChr.uc.js:143:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got browser origin: chrome [Geckium_themesChr.uc.js:154:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Added theme info to grid!  
Object { file: "Geckium_Tan_Non_Aero.crx", browser: "chrome", name: "Geckium-tan (Non-aero)", description: "A non-aero version of the Geckium-tan theme!", version: "1.0", banner: "images/theme_ntp_background.png", color: (3) […], icon: undefined }
[Geckium_themesChr.uc.js:167:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Attempting to read the manifest of Lovers+in+the+Moon+by+Mariana+Luna.crx [Geckium_themesChr.uc.js:51:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got response from manifest:  
Response { type: "basic", url: "jar:file:///C:/Users/Fishy/AppData/Roaming/Mozilla/Firefox/Profiles/sl42x965.default-esr-1711493313018/chrThemes/Lovers+in+the+Moon+by+Mariana+Luna.crx!/manifest.json", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers(2), body: ReadableStream, bodyUsed: false, hasCacheInfoChannel: false }
[Geckium_themesChr.uc.js:54:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got valid theme manifest:  
Object { manifest_version: 2, theme: {…}, name: "ChromeTheme.net", version: "1", description: "" }
[Geckium_themesChr.uc.js:60:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got theme name and description: ChromeTheme.net: [Geckium_themesChr.uc.js:96:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got theme banner: images/theme_ntp_background.png, 255,255,255 [Geckium_themesChr.uc.js:125:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got theme icon: undefined [Geckium_themesChr.uc.js:143:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got browser origin: chrome [Geckium_themesChr.uc.js:154:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Added theme info to grid!  
Object { file: "Lovers+in+the+Moon+by+Mariana+Luna.crx", browser: "chrome", name: "ChromeTheme.net", description: "", version: "1", banner: "images/theme_ntp_background.png", color: (3) […], icon: undefined }
[Geckium_themesChr.uc.js:167:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Attempting to read the manifest of New_Name.crx [Geckium_themesChr.uc.js:51:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got response from manifest:  
Response { type: "basic", url: "jar:file:///C:/Users/Fishy/AppData/Roaming/Mozilla/Firefox/Profiles/sl42x965.default-esr-1711493313018/chrThemes/New_Name.crx!/manifest.json", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers(2), body: ReadableStream, bodyUsed: false, hasCacheInfoChannel: false }
[Geckium_themesChr.uc.js:54:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got valid theme manifest:  
Object { manifest_version: 2, theme: {…}, name: "ThemeBeta.com", version: "1", description: "" }
[Geckium_themesChr.uc.js:60:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got theme name and description: ThemeBeta.com: [Geckium_themesChr.uc.js:96:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got theme banner: images/theme_ntp_background.png, 4,4,4 [Geckium_themesChr.uc.js:125:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got theme icon: undefined [Geckium_themesChr.uc.js:143:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Got browser origin: chrome [Geckium_themesChr.uc.js:154:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)
CRX getThemes: Added theme info to grid!  
Object { file: "New_Name.crx", browser: "chrome", name: "ThemeBeta.com", description: "", version: "1", banner: "images/theme_ntp_background.png", color: (3) […], icon: undefined }
[Geckium_themesChr.uc.js:167:37](chrome://userchrome/content/JS/Geckium_themesChr.uc.js)

**Comment by fishcelery4894** [comment]
wait let me check settings

**Comment by angelbruni** [comment]
Maybe it would be better if they join the Discord, I feel like, because this is weird indeed.

**Comment by dominichayesferen** [comment]
https://discord.gg/furcbfY6rW

**Comment by dominichayesferen** [comment]
since we can't replicate, makes sense to add that.

**Comment by fishcelery4894** [comment]
also off-topic scroll bars are modern

heres what i see
![image](https://github.com/user-attachments/assets/20b55077-0cbf-46c4-8c61-72f43739a102)

**Comment by fishcelery4894** [comment]
gonna join the cord
