### ISSUE TITLE
Chrome theme NTP background color is incorrect

### ISSUE THREAD

**Issue by iminonet** [angelbruni/Geckium#214]
Theme: [Honeycomb Chrome Theme](https://chromewebstore.google.com/detail/honeycomb-chrome-theme/ihhhgnjnpmjaikooiahhhlemccommcml)
Geckium version: **b0.20.0** (i havent updated yet)

How its supposed to look like:
![unnamed](https://github.com/user-attachments/assets/68bf6eb0-e592-477c-adf1-bc9d4669be26)

How it looks like on Geckium:
![image](https://github.com/user-attachments/assets/2c2e5604-c904-4de8-9bcf-2e6edfc7b9a6)

**Comment by angelbruni** [comment]
Fixed, will be in the next update.
