### ISSUE TITLE
CRX theme icons are not getting tinted properly

### ISSUE THREAD

**Issue by aubymori** [angelbruni/Geckium#217]
Geckium:
![image](https://github.com/user-attachments/assets/ee0f87a3-bfe4-46a2-aec1-7258af89926b)

Chrome:
![unnamed](https://github.com/user-attachments/assets/cbbb7b15-981e-4af7-9394-7c0d7065437a)

Theme: https://chromewebstore.google.com/detail/twilight-sparkle-theme/ifilfgjjmpfafopkhdbcgnoplfphdhbj

**Comment by angelbruni** [comment]
Issue is in the HSL shift
The fill colour is `rgb(0,0,0)` but it should be white due to
```json
"tints":{
    "buttons":[0,0,0.96]
}
```
Needs to be investigated.

**Comment by angelbruni** [comment]
![image](https://github.com/user-attachments/assets/85e347c8-0ad4-4c93-8ef8-e921c9d484d3)
Fixed in commit https://github.com/angelbruni/Geckium/commit/af4b5a2f971d03897f6982faf85c2085b60c9a53
