### ISSUE TITLE
How do i install .crx files

### ISSUE THREAD

**Issue by LPMhub** [angelbruni/Geckium#218]
it said that you can install chrome themes and how i do it's says it's compatible with chromium browsers and firefox is not

**Comment by dominichayesferen** [comment]
https://github.com/angelbruni/Geckium#:~:text=To%20improve%20your%20Geckium%20experience%2C%20you%20should%20also%20install%20Tampermonkey%20and%2C%20using%20Tampermonkey%2C%20install%20the%20official%20Geckium%20UserScript%20for%20enhanced%20functionality.

**Comment by dominichayesferen** [comment]
Namely the userScript linked in the instructions

**Comment by LPMhub** [comment]
thanks
