### ISSUE TITLE
Bug: Themes thumbnail url missing quotes

### ISSUE THREAD

**Issue by iminonet** [angelbruni/Geckium#220]
Geckium Version: b0.20.1

The themes thumbnail has a background-image code for returning the NTP background image of the theme for the thumbnail.
![image](https://github.com/user-attachments/assets/fc40f86a-8ab7-4f54-8952-4301313cd8a3)
but it does not include quotes, causing it to break and return a "Invalid properties" error.

When you manually add quotes like geckium's variables, it works.
![image](https://github.com/user-attachments/assets/7cca7765-3d26-4cad-9c48-dfa6150df11d)

**Comment by angelbruni** [comment]
Damn uou are really smashing all the bugs, will try fixing this tomorrow, thanks.
Also could you give ne that theme just in case?

**Comment by angelbruni** [comment]
Fixed in commit https://github.com/angelbruni/Geckium/commit/cd0af0e599c3a7de106722b22831fa5770fe3e34, thank you so much for your report!
