### ISSUE TITLE
ACCURACY ISSUE - Google Chrome 4.0 vs. Geckium 4.0

### ISSUE THREAD

**Issue by Classic-Windows-69** [angelbruni/Geckium#224]
The original google chrome 4.0 is on the left. Geckium's version of 4.0 is on the right.
![OG-4 0-vs-GK-4 0](https://github.com/user-attachments/assets/cadc7868-1d6e-44c9-b096-0f3d74686f9a)

**Comment by angelbruni** [comment]
Hello! Before pointing out inaccuracies, make sure to get the exact same version that Geckium displays a certain design to be based on!
