### ISSUE TITLE
Weird theming at Incognito Mode

### ISSUE THREAD

**Issue by SoftwareType** [angelbruni/Geckium#228]
While I was studying I found this problem on specific at Incognito Mode. I don't know why is it happening, however, because of how bright this screen currently is, I could notice that the background seems to be correct, but the tabs aren't. Can't tell about the New Tab button tho

![image](https://github.com/user-attachments/assets/8a574299-ea7f-4493-b70a-4729542af7d3)

Is this just on this specific case?

**Comment by angelbruni** [comment]
Vou investigar, valeu :P

**Comment by dominichayesferen** [comment]
ah whoops guess we forgot to override inactive tab background in _systhemes.scss.

**Comment by angelbruni** [comment]
Corrigido no commit https://github.com/angelbruni/Geckium/commit/e0ea6fe34d2a2ad0fc4ac0ebd96241cbd12ae91e. Obrigado por reportar :D
