### ISSUE TITLE
black titlebar buttons when using specific themes.

### ISSUE THREAD

**Issue by Classic-Windows-69** [angelbruni/Geckium#230]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozilla firefox

### What Operating System are you running Geckium on?

Windows 10 Version 22H2 (OS Build 19045.4894)

### Summarise the issue

when using specific light themes using the older chrome layouts provided.
(In the screenshot included, I've highlighted the two themes that contain this behavior, however there could be more that do this that I simply haven't discovered yet)

### Screenshots

![image](https://github.com/user-attachments/assets/4b636d74-565f-4da1-9d23-6151dcc9cf17)

### How do you reproduce the bug/inaccuracy?

Step 1: Select any layout that uses the older button style (1.0 - 6.0.453)
Step 2: Apply these specific themes: 
https://chromewebstore.google.com/detail/fade-to-white-skin-by-ska/ckagignfngcobnpabflbjdcpnegiifcj
https://chromewebstore.google.com/detail/fade-to-white-skin-by-ska/ckagignfngcobnpabflbjdcpnegiifcj
https://chromewebstore.google.com/detail/fade-to-white-skin-by-ska/ckagignfngcobnpabflbjdcpnegiifcj
https://chromewebstore.google.com/detail/fade-to-bright-aero-skin/iniphhdbdangomdllnbbhhkofoggidgc

### Expected behaviour or design

Have a tinted blue gradient, or white gradient used for the buttons instead of pure black.

### Additional Context

The "accommodate chromium themes to designs they weren't designed for" option does nothing when using these specific themes.
A similar thing happens with Skarv's dark themes when using the older layouts.

**Comment by angelbruni** [comment]
Thanks for your report, I will look into this tomorrow :)

**Comment by dominichayesferen** [comment]
My immediate suspicion is that this is actually intentional on the Chromium Theme developer's part, which... nothing we can really do about that unfortunately if so.

**Comment by dominichayesferen** [comment]
Upon further inspection, this is intentional behaviour by your Chromium Themes.
![Screenshot_20241023-025729](https://github.com/user-attachments/assets/f2af7280-ff19-436a-8def-9c65c8505547)
