### ISSUE TITLE
New Tab dosent show since homepage.xhtml dosent exist

### ISSUE THREAD

**Issue by ranvirsi1** [angelbruni/Geckium#233]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows 7

### Summarise the issue

the new tab page fails to load since its saying the file is missing 

### Screenshots

![image](https://github.com/user-attachments/assets/9c10fb65-ad04-4f2c-bbb0-fccfdb60c3ec)

### How do you reproduce the bug/inaccuracy?

1. install geckium
2. open a new tab

### Expected behaviour or design

it should have shown the new tab

**Comment by angelbruni** [comment]
It's mentioning a path that we don't use. It's conflicting with a previously installed theme.
**Delete** the chrome folder and install Geckium again. Then report back here.

**Comment by ranvirsi1** [comment]
got it thanks!
