### ISSUE TITLE
Downloads bar - estimated time not readable while in dark mode

### ISSUE THREAD

**Issue by XdekTV** [angelbruni/Geckium#239]
### Before sending your suggestion

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

r3dfox 130.0.1rc

### What Operating System are you running Geckium on?

Windows 10 (modded into 7 manually)

### What would you like to suggest for Geckium?

When downloading any file, that shows an estimated time for it to download, the text is black while in dark mode.

### Additional Context

![obraz](https://github.com/user-attachments/assets/a6d6808d-8ee5-447a-bfe3-ca8aede31962)

**Comment by SoftwareType** [comment]
What is your theme

**Comment by XdekTV** [comment]
> This is because, at least back then, themes didn't have the capability of changing the estimate time colour. If you can find a version of Chromium in which it becomes possible, send it here, even if it's a version that isn't in Geckium, as it may be added in the future anyways.

oh alright, didn't know. thanks!

**Comment by angelbruni** [comment]
Chromium and its quirks :P
