### ISSUE TITLE
"Blank" Auto-Suggestions (Chrome 25, Mozilla Firefox)

### ISSUE THREAD

**Issue by TheMaker69420** [angelbruni/Geckium#241]
### Before reporting your issue

- [ ] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [ ] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox (131.0.3)

### What Operating System are you running Geckium on?

Windows 11 Home

### Summarise the issue

the text *looks* blank, but it is simply white text on white text. this also happens on dark mode, and every design.

### Screenshots

Light Mode: 
![image](https://github.com/user-attachments/assets/7abc3fc2-b48a-4a15-ba57-24d0041aaf17)

Dark Mode:
![image](https://github.com/user-attachments/assets/e16c49ea-c68f-4106-b4cb-c3a25dd3dd96)

### How do you reproduce the bug/inaccuracy?

1. search on google/press the search button
2. some suggestions are completely blank

### Expected behaviour or design

the auto-suggestions should be in black text, so they're readable

### Additional Context

happens every time i press the search bar

**Comment by angelbruni** [comment]
Colour in light mode is intended (Chromium did that), colour in dark mode isn't.

**Comment by angelbruni** [comment]
Also for clarification, are you talking about the empty gap, or the text colour of the text on the right side?

**Comment by TheMaker69420** [comment]
i'm terribly sorry, i should have clarified. i believe it's the empty gap
![image](https://github.com/user-attachments/assets/3249e4a6-6ac4-4e79-9390-8664a39445a1)

**Comment by angelbruni** [comment]
In that case, it has been fixed, please update Geckium
- Grab it from https://github.com/angelbruni/Geckium/releases;
- Delete the ENTIRE `chrome` ONLY from the Profile folder;
- Use the new `chrome` folder from the new build;
- Restart Firefox;
- Report back :)

**Comment by TheMaker69420** [comment]
working as expected. thanks so much! 
![image](https://github.com/user-attachments/assets/e64845a1-aebb-4903-b027-b44805d954e3)

**Comment by angelbruni** [comment]
Enjoy! :D
