### ISSUE TITLE
Misaligned suggestions in addressbar 

### ISSUE THREAD

**Issue by dominichayesferen** [angelbruni/Geckium#242]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Feren OS (Linux)

### Summarise the issue

Look at the chromium suggestion in the screenshot below. 

### Screenshots

![image](https://github.com/user-attachments/assets/0fdf86ef-bcd3-424b-ba94-0c30a2952a16)

### How do you reproduce the bug/inaccuracy?

yes.

### Expected behaviour or design

They'd all be aligned.

**Comment by angelbruni** [comment]
Fixed.
