### ISSUE TITLE
Pinned tab favicons aren't centered

### ISSUE THREAD

**Issue by dominichayesferen** [angelbruni/Geckium#249]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Feren OS (Linux)

### Summarise the issue

The icons for pinned tabs ARE NOT center aligned.

### Screenshots

![image](https://github.com/user-attachments/assets/227a0e32-70c2-4646-99ae-570eade1a1f4)

### How do you reproduce the bug/inaccuracy?

1. Pin a tab

### Expected behaviour or design

The tab's favicon will be properly centered. 

### Additional Context

Actual Chrome for reference:
![image](https://github.com/user-attachments/assets/332861db-a2d5-4f83-b1cc-20a705490140)

**Comment by angelbruni** [comment]
Huh I didn't know they would stick together with unpinned tabs

**Comment by angelbruni** [comment]
Fixed.
