### ISSUE TITLE
Pinned tabs aren't connected to unpinned tabs

### ISSUE THREAD

**Issue by dominichayesferen** [angelbruni/Geckium#250]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Feren OS (Linux)

### Summarise the issue

Pinned tabs should be connected to unpinned ones, just like unpinned tabs are connected to unpinned tabs and pinned tabs are connected to pinned tabs respectively. 

### Screenshots

![image](https://github.com/user-attachments/assets/2882046c-da39-40ad-9305-fa0a9f1d5242)

### How do you reproduce the bug/inaccuracy?

1. Pin a tab
2. Unpin another tab besides it

### Expected behaviour or design

![image](https://github.com/user-attachments/assets/ba6245dd-2174-4577-91f4-7cca067764f7)
![image](https://github.com/user-attachments/assets/7b8226a0-e9d7-4633-9da7-2931314b0bd7)
![image](https://github.com/user-attachments/assets/aeb2cbca-8b0d-466a-8663-380550802582)
![image](https://github.com/user-attachments/assets/2b075399-bd99-41a0-8f6e-26dce13bb1a6)
![image](https://github.com/user-attachments/assets/49bdf188-bcdc-4dee-83f3-b36737e832bb)

**Comment by angelbruni** [comment]
Fixed.
