### ISSUE TITLE
Close button of tabs is in wrong place

### ISSUE THREAD

**Issue by WindowsDefen517** [angelbruni/Geckium#254]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox 115.16.1 ESR

### What Operating System are you running Geckium on?

Windows 7 x64 Ultimate

### Summarise the issue

The close button is at the wrong place. When there are a lot of tabs

### Screenshots

![r3dfox_gue659s3Js](https://github.com/user-attachments/assets/8b06170e-57c5-410f-939c-cddb1153cea9)

### How do you reproduce the bug/inaccuracy?

1. Open a lot of tabs
2. go with the mouse on a tab
3. Done

### Expected behaviour or design

on Google Chrome 28 it's supposed to look that.
![image](https://github.com/user-attachments/assets/52ee07c9-fdc7-4528-b443-2afd2646efa3)
I can't boot older Google chrome so i don't know if it's the same.

### Additional Context

The issue is with all designs of geckium

**Comment by angelbruni** [comment]
Fixed in commit https://github.com/angelbruni/Geckium/commit/9ee78adb47f6f6fd826a77a22d2d9250cf7916a5.
