### ISSUE TITLE
Cannot click on a tab when a lot of is open.

### ISSUE THREAD

**Issue by WindowsDefen517** [angelbruni/Geckium#255]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox 115.16.1 ESR

### What Operating System are you running Geckium on?

Windows 7 x64 Ultimate

### Summarise the issue

I cannot click on any tab when a lot of is open

### Screenshots

![image](https://github.com/user-attachments/assets/8274fee7-d286-42ec-a349-d470cfe46377)

### How do you reproduce the bug/inaccuracy?

1. Open a lot of tabs.
2. Try to open one.
3. Done.

### Expected behaviour or design

Open the tab.

**Comment by angelbruni** [comment]
I guess I can add an element just for hitbox

**Comment by WindowsDefen517** [comment]
Maybe idk, and really Thanks you for your project it's incredible :DDD !

**Comment by angelbruni** [comment]
You are welcome :)
And thank you for your reports, it really helps me :D

**Comment by angelbruni** [comment]
Fixed in commit https://github.com/angelbruni/Geckium/commit/1c91881f569d01b5155c33b8fe583d2bc91863a0 by creating a hitbox element: https://youtu.be/DTX4459XwxI

**Comment by WindowsDefen517** [comment]
wow good job!! :D and funny mouse xd

**Comment by angelbruni** [comment]
Thank you xd
