### ISSUE TITLE
Icon is showed and at the wrong place when a lot of tabs is open.

### ISSUE THREAD

**Issue by WindowsDefen517** [angelbruni/Geckium#256]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox 115.16.1 ESR

### What Operating System are you running Geckium on?

Windows 7 x64 Ultimate

### Summarise the issue

The icon is showed when a lot of tabs is open.

### Screenshots

![image](https://github.com/user-attachments/assets/f5ee8cc7-5e5c-49c8-8b14-f62e305c6989)

### How do you reproduce the bug/inaccuracy?

1. Go on any websites with a icon
2. Open a lot of tabs.
3. Done.

### Expected behaviour or design

Show only when some tabs is open. 
![image](https://github.com/user-attachments/assets/3146ade3-4963-4f9a-aee7-dcf86c41b4f8)

**Comment by angelbruni** [comment]
Fixed in commit https://github.com/angelbruni/Geckium/commit/9ee78adb47f6f6fd826a77a22d2d9250cf7916a5.
