### ISSUE TITLE
(Please remove if duplicate) CLOSE BUTTON MISSALINGNED WHEN TABS SQUISHED.

### ISSUE THREAD

**Issue by Classic-Windows-69** [angelbruni/Geckium#269]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows 10 Version 22H2 (OS Build 19045.4894)

### Summarise the issue

When an exuberant amount of  tabs are open, the close button begins to become misaligned. The more tabs that are opened, the more prominent the effect.

### Screenshots

![image](https://github.com/user-attachments/assets/0f363181-587a-4a89-8b09-4e12cb874829)
![image](https://github.com/user-attachments/assets/cb9b9840-4d13-4160-bd79-41e1b63ff4b2)

### How do you reproduce the bug/inaccuracy?

1. Open geckium
2. Have 40 or more tabs open.

### Expected behaviour or design

Have the close button do this instead:
![image](https://github.com/user-attachments/assets/468481eb-724f-45df-aa79-207c01f02386)

### Additional Context

-Shouldn't be an issue unless you are a tab hoarder (such as myself)

**Comment by angelbruni** [comment]
At that point the icon shouldn't even be showing up, this must be some sort of bug in the code...

**Comment by Classic-Windows-69** [comment]
Is your display resolution 1920 by 1080?
If so, then more than 45 tabs + some pinned tabs should do the trick (on windows). I haven't tried this on any other OS. (I'd test on VMs, but I have storage space to worry about)

**Comment by angelbruni** [comment]
![image](https://github.com/user-attachments/assets/60cb3b3d-56b9-47ed-9ccc-ba3245f161b1)
I still can't replicate it.
Would you mind showing me your Geckium version, just so I am sure I am not trying to find something that doesn't exist anymore:
Geckium Settings -> About

**Comment by Classic-Windows-69** [comment]
![image](https://github.com/user-attachments/assets/8f321cef-867c-4b14-9842-7def7f0d9c01)

**Comment by angelbruni** [comment]
> ![image](https://private-user-images.githubusercontent.com/134807542/380921807-8f321cef-867c-4b14-9842-7def7f0d9c01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNTg4NzQsIm5iZiI6MTczMDE1ODU3NCwicGF0aCI6Ii8xMzQ4MDc1NDIvMzgwOTIxODA3LThmMzIxY2VmLTg2N2MtNGIxNC05ODQyLTdkZWY3ZjBkOWMwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQyMzM2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTc1YWZlZmUyMjhlMGY1NDYxOTY1YzUxN2NkYmMwNmU2NGZhYTA1Mjg5MTI4MTczZTE0OGQ5ZDE4MWY0ZTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mYtYcKFhzNce4XKtylRNp_FI8ldX_p1HtwIJpBIG2ak)

This is not showing Geckium's version

**Comment by Classic-Windows-69** [comment]
![image](https://github.com/user-attachments/assets/04626a69-c0d4-49a9-b100-80e12d65590f)
![image](https://github.com/user-attachments/assets/ac87a676-7c51-462d-9a2d-d27c8ffa12d6)

**Comment by angelbruni** [comment]
Okay, thank you very much.
I wonder why I just can't seem to replicate it...

**Comment by Classic-Windows-69** [comment]
Perhaps it's because you are on 11?
(or were those later screenshots on a win10 vm?)

**Comment by angelbruni** [comment]
It shouldn't really matter.
Firefox treats 11 as 10, and there isn't any OS-specific code in my recent addition to the tabs code.
I only used a VM so I could test `1920x1080`.

**Comment by Classic-Windows-69** [comment]
Oh, another thing, are those all new tabs? If so, that's might be the reason why you can't replicate. a new tab doesn't have a favicon, and this issue only seems to affect tabs with favicons.

**Comment by angelbruni** [comment]
> Oh, another thing, are those all new tabs? If so, that's might be the reason why you can't replicate. a new tab doesn't have a favicon, and this issue only seems to affect tabs with favicons.

No, these are all `https://www.google.com` tabs.

**Comment by Classic-Windows-69** [comment]
...hold on, i noticed something else, there's a specific point in tab squishment that the issue fixes it's self, however if you have an amout a little below that, the issue comes back again. perhaps you should carefuly close each tab, and let me know if you are able to replicate then.

**Comment by Classic-Windows-69** [comment]
It also is fixed if you switch tabs, however, if you were to stay on the same tab, and resize your window, the issue occurs.

**Comment by angelbruni** [comment]
> ...hold on, i noticed something else, there's a specific point in tab squishment that the issue fixes it's self, however if you have an amout a little below that, the issue comes back again. perhaps you should carefuly close each tab, and let me know if you are able to replicate then.

If you are talking about some tabs having the favicon and others excluding the favicon depending on the amount of tabs, that's how it was in Chromium too.

**Comment by Classic-Windows-69** [comment]
I've noticed something that might be the reason why you are having trouple replicating, the issue is very unpredictable, sometimes it does it and sometimes it doesn't. it's most likely to happen if you were to go back into fullscreen after messing with your window size and messing with tab amount.

**Comment by angelbruni** [comment]
I think it has to do with what I just talked about, if this is the case, I can try improving this a little more.
Thank you very much, we ended up figuring out what was going on, I guess, hopefully :P

**Comment by Classic-Windows-69** [comment]
Your welcome. I just figured this is an issue I should bring to your attention to fix when ever you're able.
(I personally don't view it as that high of a priority, as it is still usable, however an issue is still an issue, if you know what I mean)

**Comment by angelbruni** [comment]
Yep, definitely always report everything :)

**Comment by angelbruni** [comment]
It was another issue. Fixed it in commit https://github.com/angelbruni/Geckium/commit/e9de2e7ad06b212a0aeae7b580051dc4e6b09dec, thanks.
