### ISSUE TITLE
I think the extension icons are bigger than this

### ISSUE THREAD

**Issue by robisme** [angelbruni/Geckium#271]
### Before sending your suggestion

- [ ] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows 10

### What would you like to suggest for Geckium?

![スクリーンショット (43)](https://github.com/user-attachments/assets/53a0f71d-967b-4307-a568-1e97893b6725)

**Comment by dominichayesferen** [comment]
side tangent: I see your alt text is in Japanese.

If you know Japanese, we are looking for a Japanese localisation of Geckium.

**Comment by angelbruni** [comment]
I have had this reported before on Discord, and yes, I think Chromium did have them larger for extensions...
I think I can reduce the padding causing icons to be larger only for buttons related to extensions o.o

**Comment by angelbruni** [comment]
Added in https://github.com/angelbruni/Geckium/commit/0777bbf9ef1386ba22873267db850ca0ccbdced9:
This commit styles the badges and also makes the icons in extension toolbarbuttons larger.
