### ISSUE TITLE
Tooltips are greatly offset vertically from the cursor

### ISSUE THREAD

**Issue by aubymori** [angelbruni/Geckium#272]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox 128.2.0esr

### What Operating System are you running Geckium on?

Windows 10 IoT Enterprise LTSC 2021, 19044.4561

### Summarise the issue

Tooltips are greatly vertically offset from the cursor compared to vanilla Firefox.

### Screenshots

Geckium:
![image](https://github.com/user-attachments/assets/b85e3a85-e6b8-4058-b334-44d3134d15b8)
Vanilla Firefox:
![image](https://github.com/user-attachments/assets/a287ba50-06c7-49fc-a398-96417aa51fe8)

### How do you reproduce the bug/inaccuracy?

Hover over an HTML element with the `title` attribute set, e.g. the search box on the Google homepage.

### Expected behaviour or design

The tooltip should be closer to the cursor.

**Comment by angelbruni** [comment]
Fixed in commit https://github.com/angelbruni/Geckium/commit/798aa55871c25835863825b2afa3b371e098fcc2. Thank you.
Now to hope that `margin-top` wasn't something important lol...
