### ISSUE TITLE
Avatar position is wrong

### ISSUE THREAD

**Issue by ikkqqstudio** [angelbruni/Geckium#273]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [x] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

BrowserWorks Waterfox

### What Operating System are you running Geckium on?

Windows 10 Pro x64

### Summarise the issue

Why is the Avatar position is wrong?
Who did this?

### Screenshots

![image](https://github.com/user-attachments/assets/f63a3f19-e111-4c2c-9f6c-5385a6a267f9)

### How do you reproduce the bug/inaccuracy?

i don't know what to say

### Expected behaviour or design

When i turned on Avatar mode
but then the avatar is in wrong position

### Additional Context

i don't know what to say

**Comment by angelbruni** [comment]
Because you have to move it yourself.
In Geckium, it's a real button.
Right click toolbar -> Customize Toolbar... -> drag it.
