### ISSUE TITLE
I'm using Windows 7 and the tooltips and scrollbars are weird.

### ISSUE THREAD

**Issue by robisme** [angelbruni/Geckium#292]
### Before reporting your issue

- [ ] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows 7

### Summarise the issue

I'm using Windows 7 and the tooltips and scrollbars are weird.

### Screenshots

![bandicam 2024-11-03 21-43-55-909](https://github.com/user-attachments/assets/04e92e8d-d563-4a58-b633-75828797827a)
![bandicam 2024-11-03 21-48-33-528](https://github.com/user-attachments/assets/6aab00d8-5f36-4292-8627-1b602b8ae4e2)

### How do you reproduce the bug/inaccuracy?

Use Windows 7

### Expected behaviour or design

![bandicam 2024-11-03 22-49-34-333](https://github.com/user-attachments/assets/b684ebc4-4586-4007-bffb-4dc3dec9ba3b)
![bandicam 2024-11-03 22-49-55-610](https://github.com/user-attachments/assets/2d9ae9da-679e-426e-a778-99ab1945f913)

### Additional Context

No response

**Comment by ApertureLabs4194** [comment]
are you using windows 10 or 7

**Comment by ApertureLabs4194** [comment]
weird, im not having that issue

**Comment by robisme** [comment]
I wonder why

**Comment by dominichayesferen** [comment]
> ### Before reporting your issue
> 
>     * [ ]  My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
> 
>     * [x]  My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
> 
>     * [x]  I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium
> 
> 
> ### What browser are you running Geckium on?
> 
> Mozilla Firefox
> ### What Operating System are you running Geckium on?
> 
> Windows 7
> ### Summarise the issue
> 
> I'm using Windows 7 and the tooltips and scrollbars are weird.
> ### Screenshots
> 
> ![bandicam 2024-11-03 21-43-55-909](https://private-user-images.githubusercontent.com/171232301/382575735-04e92e8d-d563-4a58-b633-75828797827a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MzA3NzcsIm5iZiI6MTczMDgzMDQ3NywicGF0aCI6Ii8xNzEyMzIzMDEvMzgyNTc1NzM1LTA0ZTkyZThkLWQ1NjMtNGE1OC1iNjMzLTc1ODI4Nzk3ODI3YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxODE0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDhlZjI1ZGUzNmRlNTMxZTg2OWVhYmJkZDk4NjU2NGRhYzU0ZTgyMzYwYTE2ZGU3M2NhZjJiMDVhNjNhYzA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sqH-_Y779z_UDLYKVthxkdhNqO7MOhLMf-lfJQ8pesQ) ![bandicam 2024-11-03 21-48-33-528](https://private-user-images.githubusercontent.com/171232301/382575739-6aab00d8-5f36-4292-8627-1b602b8ae4e2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MzA3NzcsIm5iZiI6MTczMDgzMDQ3NywicGF0aCI6Ii8xNzEyMzIzMDEvMzgyNTc1NzM5LTZhYWIwMGQ4LTVmMzYtNDI5Mi04NjI3LTFiNjAyYjhhZTRlMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxODE0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTVlZGM2YTU2YzRlYzM4YzQ2MTc2MDRiZGI3NmViYmEzZTY3Zjg1NDY4YzFlNzQwZmNiM2RmNGFlMDViNWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WAjVb0-NrYfqzaQx5N8z6fEAFDcQ8XHiAStIvYMpAYM)
> ### How do you reproduce the bug/inaccuracy?
> 
> Use Windows 7
> ### Expected behaviour or design
> 
> ![bandicam 2024-11-03 22-49-34-333](https://private-user-images.githubusercontent.com/171232301/382577249-b684ebc4-4586-4007-bffb-4dc3dec9ba3b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MzA3NzcsIm5iZiI6MTczMDgzMDQ3NywicGF0aCI6Ii8xNzEyMzIzMDEvMzgyNTc3MjQ5LWI2ODRlYmM0LTQ1ODYtNDAwNy1iZmZiLTRkYzNkZWM5YmEzYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxODE0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTkzZTU3Y2FmZWQ1ZjFiOWU4MWJiNGU1YmQxZmU0ZTI1Yjk0NmEwMzBiODA2YmM1ODBmM2IzYjY5ZmUwNmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QDjEQB9VsJisCryW4fZBi_57159Rcm3wXOXOR2dyKpI) ![bandicam 2024-11-03 22-49-55-610](https://private-user-images.githubusercontent.com/171232301/382577255-2d9ae9da-679e-426e-a778-99ab1945f913.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MzA3NzcsIm5iZiI6MTczMDgzMDQ3NywicGF0aCI6Ii8xNzEyMzIzMDEvMzgyNTc3MjU1LTJkOWFlOWRhLTY3OWUtNDI2ZS1hNzc4LTk5YWIxOTQ1ZjkxMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxODE0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGIxZWVjMWYzOWJiMzM4NzQ5YjYyNDVlOGE0MjhhMDkyYjUwZGRjNDNhZGUyMGRlZmJiYWM5Zjc4NTFiNWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zK9pD1PqwJQpaqeu-6nKBBa5dclGZ4AmQeXHiljLGbk)
> ### Additional Context
> 
> No response

Scrollbars are an intentional choice in Upstream Firefox. Likely, same with the tooltips. Therefore, this isn't something we can fix as it's not our problem.

**Comment by dominichayesferen** [comment]
Scrollbars have an upstream issue - they are an intentional Firefox bug.
https://bugzilla.mozilla.org/show_bug.cgi?id=1755605

**Comment by robisme** [comment]
not working

**Comment by robisme** [comment]
not working

**Comment by robisme** [comment]
I tried it on another Windows 7 computer and the same thing happened.

**Comment by angelbruni** [comment]
Is this with or without Native Controls Patch?

**Comment by robisme** [comment]
it's working!! thank you so much!
