### ISSUE TITLE
Dead tabs' favicons don't change

### ISSUE THREAD

**Issue by dominichayesferen** [angelbruni/Geckium#295]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [ ] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Feren OS (Linux)

### Summarise the issue

The favicon of dead tabs isn't changed to the dead Jim.

### Screenshots

![image](https://github.com/user-attachments/assets/74b3a521-4156-44c7-be91-d1e80139883b)

### How do you reproduce the bug/inaccuracy?

1. Go to the URL of a new tab page thumbnail
2. or find any other way to crash a tab

### Expected behaviour or design

The favicon is replaced by the dead Jim, and maybe also having the new favicon slide in like era-appropriate Chromium.

**Comment by angelbruni** [comment]
Can I see how dead jim looks like in the tab?

**Comment by dominichayesferen** [comment]
![image](https://github.com/user-attachments/assets/48f51b35-5264-40bb-9ca9-45c2f9cbfec5)
![image](https://github.com/user-attachments/assets/48ea274d-44d9-48b5-8d58-15279b2ab0f3)
![image](https://github.com/user-attachments/assets/273fabd2-616d-4ea1-8d14-4ecec03cde99)

**Comment by angelbruni** [comment]
Thanks, on my way to find the favicon.........

**Comment by angelbruni** [comment]
Nevermind, that was easy, it's called `sadfavicon.png`

**Comment by dominichayesferen** [comment]
https://youtu.be/WNDrPebR6vE?feature=shared

**Comment by angelbruni** [comment]
Added in commit https://github.com/angelbruni/Geckium/commit/9c92fed7d1fc22846631383810d2c901e8814b67.
