### ISSUE TITLE
Inactive Tab Text always black no matter the theme

### ISSUE THREAD

**Issue by Gold-Phoenix** [angelbruni/Geckium#297]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

R3dfox

### What Operating System are you running Geckium on?

Windows 7

### Summarise the issue

No matter what theme i select inside of geckium or no matter if i chanage it from light to dark mode, the inactive tab text is always black, whenever my background goes dark i cannot see any tab text.

The active tab doesnt have this issue, if you could point me towards the correct file or something i can see if i can fix it.

### Screenshots

![Untitled](https://github.com/user-attachments/assets/56c218e6-8d5d-45e8-b523-961efd0576db)

### How do you reproduce the bug/inaccuracy?

1. Install r3dfox
2. Install tampermonky and the official Geckium UserScript for enhanced functionality
3. Install Geckium
4. Launch r3dfox

### Expected behaviour or design

I expected the text to change to white once the theme was changed to dark mode

**Comment by angelbruni** [comment]
Your Geckium is not even loaded properly.
Get it from Releases.

**Comment by Gold-Phoenix** [comment]
I did, im using the 1.9.1 build

**Comment by angelbruni** [comment]
> I did, im using the 1.9.1 build

Your screenshot does not show Geckium from release and the version means nothing because it's just the last time the version number was updated in the sourcecode.

This is the correct download: https://github.com/angelbruni/Geckium/releases/download/b0.20.9.1/Geckium_Public_Beta_1.9.1.zi

**Comment by Gold-Phoenix** [comment]
Thats literally what i downloaded

**Comment by angelbruni** [comment]
Yours shows the Firefox UI, not the Chromium UI:
![image](https://github.com/user-attachments/assets/24fdd37a-d05f-4b5e-b3e8-67fcaf5f08f3)

Show your `chrome` folder for me and a screenshot from `about:support`, please.

**Comment by Gold-Phoenix** [comment]
![image](https://github.com/user-attachments/assets/6ae65ba6-ee7f-4227-96b6-7a7cdc7fe090)

**Comment by angelbruni** [comment]
I see `simpleMenuWizard` folder, did you have something else installed before?

**Comment by Gold-Phoenix** [comment]
I installed simpleMenuWizard after Geckium, i can try removing it fully

**Comment by Gold-Phoenix** [comment]
Ok, that fixed it, how strange, it didnt do that the first time

**Comment by angelbruni** [comment]
Remove it fully, then go to `about:support` and `Clear startup cache...`
Did the Geckium wizard show up when you installed Geckium? Was it broken too?

**Comment by angelbruni** [comment]
It is.
Terribly sorry for misjudging, we've been getting people left and right who don't read the README.md.
It's very annoying, I don't know why people assume the SOURCECODE has compiled files.

**Comment by angelbruni** [comment]
By the way, you can edit your toolbar to have a similar layout to Chromium's
![image](https://github.com/user-attachments/assets/20ff8b8c-b0a1-44c9-97c7-906567ff4b1e)

**Comment by angelbruni** [comment]
Nope, you can right click the titlebar (not a tab) or toolbar, it will have a `Customize toolbar...` in the right click menu.

You can then drag things that didn't exist in Chromium out of the toolbar, or if you want, you can keep them, it's all personal choice.

Chromium's layout went like this:
`[Back][Forward][Refresh][Home (Optional)][URL Bar][Extensions][Page Menu (Chromium 1-5)][Chrome Menu]`

The extension button is removable in `Geckium Settings -> Behaviour -> Hide extensions menu button`.

Enjoy.

**Comment by Gold-Phoenix** [comment]
Just some more info, the thing that breaks Geckium in SimpleMenuWizard is specifically this line in userChrome.css:

/*** Hide all inactive menu items ***/
 #mainPopupSet menuitem[disabled="true"][id][data-l10n-id] { display: none !important; }

Removing this restores Geckium to full functionality
