### ISSUE TITLE
Google Chrome themes

### ISSUE THREAD

**Issue by socketpal25** [angelbruni/Geckium#299]
### Before sending your suggestion

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows 7

### What would you like to suggest for Geckium?

Hello. In the themes option, there is an option where it directs you to the Chrome Web store, but the different browsers make it unavailable to download at least the root file. Is there a possible way to add Chrome themes to Geckium?

**Comment by dominichayesferen** [comment]
https://github.com/angelbruni/Geckium?tab=readme-ov-file#instructions

**Comment by angelbruni** [comment]
Use the userScript in the instructions that Dominic linked
