### ISSUE TITLE
Tab Recording/Microphone indicator

### ISSUE THREAD

**Issue by TheRealRysieQu** [angelbruni/Geckium#301]
### Before sending your suggestion

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

r3dfox

### What Operating System are you running Geckium on?

Windows 10 (with eXPerience)

### What would you like to suggest for Geckium?

While I was chatting with friends on VC, I noticed this microphone indicator
![EqDomj3](https://github.com/user-attachments/assets/9e8dfde6-15fc-4793-842f-768906883089)
Google Chrome had a very similar indicator to this, with nearly the same fade in, fade out animation. It can be seen here:
https://www.youtube.com/watch?v=pop2Jv6GREM

**Comment by angelbruni** [comment]
Added in https://github.com/angelbruni/Geckium/commit/8f6dbb69e59247d3e0cc177bf9af4e7925181e5c.
