### ISSUE TITLE
crx themes not showing

### ISSUE THREAD

**Issue by newfuckingplayer** [angelbruni/Geckium#302]
### Before reporting your issue

- [ ] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [ ] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows 10

### Summarise the issue

crx themes are not showing like geckium tan

### Screenshots

![image](https://github.com/user-attachments/assets/55347d3a-33ca-47d3-981f-db5a548878fa)

### How do you reproduce the bug/inaccuracy?

you dont

### Expected behaviour or design

the crx files to appear

**Comment by angelbruni** [comment]
Sorry for being annoying about this, but could you send a full screnshot of Geckium Settings about page?

**Comment by newfuckingplayer** [comment]
![image](https://github.com/user-attachments/assets/7b015af8-c06d-455b-a10f-b843224348bc)
![image](https://github.com/user-attachments/assets/bfc0dc91-0c45-48b9-87cc-0e2e911e8d1c)

**Comment by angelbruni** [comment]
Your Firefox ESR is outdated (`115.12.0` and not `115.16.1`).
Older versions can't load all types of `.crx` files.
When you update to `115.16.1`, immediately disable updates, or you will be updated to `128`, unless you don't care about Aero then there's no issue with updating.

**Comment by newfuckingplayer** [comment]
thanks!
