### ISSUE TITLE
i think this isn't supposed to be here

### ISSUE THREAD

**Issue by bas01f** [angelbruni/Geckium#304]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [ ] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox Nightly 134.0a1 (2024-11-09)

### What Operating System are you running Geckium on?

Windows

### Summarise the issue

Firefox Nightly presented this "This Time Search With" that i don't think it is there when using Geckium i guess

### Screenshots

![image](https://github.com/user-attachments/assets/9d5d3218-78d0-4593-8bb2-04b0adcbab83)
![image](https://github.com/user-attachments/assets/b9e816fd-be68-482e-8c8f-63d2c802e61e)

### How do you reproduce the bug/inaccuracy?

Nothing

### Expected behaviour or design

Nothing

### Additional Context

At least make a option that hides it

**Comment by angelbruni** [comment]
This has been fixed a couple of hours ago, you need to wait for an update, thanks :)

**Comment by angelbruni** [comment]
Update released.
