### ISSUE TITLE
Can't switch tabs if my mouse is at the top of the screen

### ISSUE THREAD

**Issue by RC569** [angelbruni/Geckium#309]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows 10

### Summarise the issue

When my cursor is at the very top of the screen, it won't switch tabs, if I move it by 1 pixel down it'll switch.

### Screenshots

![iomage](https://github.com/user-attachments/assets/22acb8e6-3d0e-4822-8d85-3d60d16590cf)
Marked it in red 

### How do you reproduce the bug/inaccuracy?

1. Put mouse at the top of the screen
2. Click

### Expected behaviour or design

The tab should switch without having to move the mouse

**Comment by angelbruni** [comment]
Meant to say top left***

**Comment by RC569** [comment]
Thanks

**Comment by angelbruni** [comment]
As a head's up, almost everything in the toolbar can be removed, so you can get rid of those gaps before and after the URL bar too.

You can right click the titlebar (not a tab) or toolbar, it will have a `Customize toolbar...` in the right click menu.

You can then drag things that didn't exist in Chromium out of the toolbar, or if you want, you can keep them and/or drag more things in, it's all personal choice.

For reference, Chromium's layout went like this:
`[Back][Forward][Refresh][Home (optional)][URL Bar][Extensions (not the extensions menu)][Page Menu (Chromium 1-5)][Chrome Menu]`

The extension button is removable in `Geckium Settings -> Behaviour -> Hide extensions menu button`.

**Comment by angelbruni** [comment]
> I will see if I can prevent the size from changing if buttons are pinned on the titlebar.

Temporary fix: https://github.com/angelbruni/Geckium/commit/8a2b7af2aacb79b7bc9585488f753180eca80a05
