### ISSUE TITLE
add uninstall

### ISSUE THREAD

**Issue by cacheninetynine** [angelbruni/Geckium#310]
### Before sending your suggestion

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [ ] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Manjaro Linux

### What would you like to suggest for Geckium?

uninstall script or button idk

**Comment by angelbruni** [comment]
Duplicate https://github.com/angelbruni/Geckium/issues/298
