### ISSUE TITLE
Translate button isn't working in designs 47+

### ISSUE THREAD

**Issue by XdekTV** [angelbruni/Geckium#312]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

r3dfox 132.0rc-2

### What Operating System are you running Geckium on?

Windows 10 21H2

### Summarise the issue

On the new tab of designs with the app button in the right upper corner (47+), the translate link doesn't work. Everything else works as expected.

### Screenshots

https://github.com/user-attachments/assets/165ffd76-bfb7-4487-9753-f5a95eb6110a

### How do you reproduce the bug/inaccuracy?

1. Apply any of the designs/New Tab styles from 47 and up
2. Press on the apps icon in the right upper corner
3. "Transtale" doesn't work

### Expected behaviour or design

Translate button should redirect to "transtale.google.com"

**Comment by angelbruni** [comment]
Guess I forgor

**Comment by angelbruni** [comment]
Ah, I put the link in the wrong place

**Comment by angelbruni** [comment]
Fixed in https://github.com/angelbruni/Geckium/commit/24f79278436ba92bbd0a8d85842dfe1a87fb9dd9. Thanks.
