### ISSUE TITLE
Missing New Tab preview for Chromium 17

### ISSUE THREAD

**Issue by XdekTV** [angelbruni/Geckium#313]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

r3dfox 132.0rc-2

### What Operating System are you running Geckium on?

Windows 10 21H2

### Summarise the issue

I know that this design just came out, but there is no preview for Chromium 17's New Tab when having the override new tab design option checked.

### Screenshots

![obraz](https://github.com/user-attachments/assets/fd8a7c1d-cf25-4a5d-a3f8-3c9a21b4923f)

### How do you reproduce the bug/inaccuracy?

1. Open Geckium Settings
2. Go to the Design or Style category (the 1st one because i don't remember how it's called)
3. Check the overriding New Tabs's style

### Expected behaviour or design

There should be an image previewing it. I would take one, but my install is a bit bugged because of some dark mode stuff.

**Comment by angelbruni** [comment]
I did indeed forget about this one :(

**Comment by XdekTV** [comment]
> I did indeed forget about this one :(

no problem, sometimes it happens lol
