### ISSUE TITLE
When unfix the Geckium extension from the extension tab (top right), the extension disapeared.

### ISSUE THREAD

**Issue by FLKS07** [angelbruni/Geckium#317]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows 11

### Summarise the issue

I unifixed the extension on the extension section on the top right of firefox and it disapeared, instead of going to the menu on the extension icon, it simply did not appear anywhere.

### Screenshots

![{E1B9CD26-283F-4464-BA89-645C6FCADD3F}](https://github.com/user-attachments/assets/1f6d2428-2254-4ed1-bc69-b6a72dae2e27)

### How do you reproduce the bug/inaccuracy?

1. Unfixed extension.
2. Disapeared

### Expected behaviour or design

Expected to go on the extension menu.
![{DC72C231-8CF3-40C9-A614-65CB88704C96}](https://github.com/user-attachments/assets/ebee8229-352f-43c4-8e48-bcf0ab562063)
Extension menu

**Comment by angelbruni** [comment]
We don't mess with extension buttons.
Do you have a sceeenshot of it not showing up in the menu?

**Comment by angelbruni** [comment]
I got that, so you have a screenshot of it not in the toolbar or the extensions menu?

**Comment by FLKS07** [comment]
The extension menu (all the extension installed in my browser) it's provided on the first screenshot. The geckium settings button (the one it disaspeared) it appeared when I installed geckium, I tried to unfix it to appear in the little menu (provided in the 2nd screenshot). Now I can't find the geckium button anywhere. Is there way to pop up the window to change the settings of geckium?
Either way thanks for the fast response.

**Comment by angelbruni** [comment]
Oh, I thought you meant TamperMonkey.
Geckium Settings is not an extension, it's visible in Customize Toolbar.
Right click the toolbar -> Customize Toolbar -> Drag it in
On that note, you can also remove the big gaps and other buttons with Customize Toolbar by dragging them out

**Comment by FLKS07** [comment]
Oh, thank you. I thought it was an extension because it appared like them. Either way thanks for the help. I really like the work you done with this project.
