### ISSUE TITLE
Download timer text too dark, maybe allow us to change the color?

### ISSUE THREAD

**Issue by Arlisbloxer05** [angelbruni/Geckium#319]
### Before sending your suggestion

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows 10 22H2

### What would you like to suggest for Geckium?

I've been using Geckium for a few days, and it's great. My only issue however is that the download bar's text is too dark, specifically the text below the file name.
![image](https://github.com/user-attachments/assets/1f56d42a-8d1c-44c3-88dd-eaa979f5b579)

I think it'd be a good idea to allow users to change the color of it for easier readability on darker themes

**Comment by angelbruni** [comment]
Duplicate, read this comment: https://github.com/angelbruni/Geckium/issues/239#issuecomment-2435206253

**Comment by angelbruni** [comment]
Also, this is something that, if I ever implement as a custom setting, it would be more for accessibility than anything, however, I am not sure how I'd do it yet.
