### ISSUE TITLE
Settings' options use the wrong paddling on Marblefox 132.0.3b1

### ISSUE THREAD

**Issue by ImSwordQueen** [angelbruni/Geckium#337]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Marblefox 132.0.3b1

### What Operating System are you running Geckium on?

Windows 10 21H2

### Summarise the issue

the options in settings use the wrong paddling compared to 115 ESR

### Screenshots

![image](https://github.com/user-attachments/assets/e22838fb-a38f-4152-9d48-c3fdfb7c3d69)

### How do you reproduce the bug/inaccuracy?

1. Open Settings

### Expected behaviour or design

Not have a huge paddling

**Comment by angelbruni** [comment]
Fixed in https://github.com/angelbruni/Geckium/commit/8c3810a5357214d9b94e8f6e8adb85a400c10f52.
