### ISSUE TITLE
window borders not following settings

### ISSUE THREAD

**Issue by psyclonepman** [angelbruni/Geckium#346]
### Before reporting your issue

- [x] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [ ] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [x] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Marble

### What Operating System are you running Geckium on?

Windows 10 (With win10to7)

### Summarise the issue

(Canary) even when having border style set to system, it uses the compact borders on most themes

### Screenshots

![image](https://github.com/user-attachments/assets/3a27b642-51a1-4f06-857e-121b56d9e699)

### How do you reproduce the bug/inaccuracy?

1. select a theme
2. go to design
3. select system borders
4. select enabled under system borders in chromium themes

### Expected behaviour or design

system borders will be applied.

**Comment by angelbruni** [comment]
You need to force it in behaviour 
![image](https://github.com/user-attachments/assets/2148b303-805c-4275-b907-8f67f5b414c0)

**Comment by angelbruni** [comment]
Please, don't do this next time. If someone else has the same question, they won't find the answer for it because the contents of the question got deleted.
