### ISSUE TITLE
"Get Started" window opens upon every new browser window

### ISSUE THREAD

**Issue by ddchampaigne** [angelbruni/Geckium#353]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows 10

### Summarise the issue

Anytime a browser window is opened, whether through the "Open In New Window" button or by starting the browser itself, the "Get Started" window opens.

### Screenshots

![image](https://github.com/user-attachments/assets/543d88f1-03aa-4040-bc9b-12fd4b232263)

### How do you reproduce the bug/inaccuracy?

1. Open Browser/click "Open In New Window" on a link
2. Get Started window appears when it shouldn't

### Expected behaviour or design

"Get Started" window shouldn't appear unless on first install

**Comment by angelbruni** [comment]
Happens if you never finish the wizard
