### ISSUE TITLE
The loading state in GSettings causes a flashbang for dark mode users

### ISSUE THREAD

**Issue by dominichayesferen** [angelbruni/Geckium#357]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Feren OS

### Summarise the issue

Yeah the disabled card look has no dark mode yet

### Screenshots

![image](https://github.com/user-attachments/assets/9e0dafcf-9181-4878-af18-2e63a07443d6)

### How do you reproduce the bug/inaccuracy?

1. Be on dark mode
2. Enter Themes page on Geckium main

### Expected behaviour or design

Dark themed walls

**Comment by angelbruni** [comment]
YES I KNEW I HAD SOMETHING TO FIX AND I KEPT FORGETTING
The colour was temporary loll

**Comment by dominichayesferen** [comment]
I guess as another bug:
The selected radio is above the 'wall'.

**Comment by angelbruni** [comment]
Fixed in https://github.com/angelbruni/Geckium/commit/189447893128f4e2a30d673c5352ade1574a8cb0 and https://github.com/angelbruni/Geckium/commit/f3f88cabed7b5643b08c8431d8cb7af2e6e981bf.
