### ISSUE TITLE
GSettings SFX's path is hardcoded

### ISSUE THREAD

**Issue by dominichayesferen** [angelbruni/Geckium#358]
### Before reporting your issue

- [ ] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [ ] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [ ] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Feren OS

### Summarise the issue

Uhh yeah:

`const SFXTick = new Audio("file:///home/brunof/.mozilla/firefox/capy8v0g.default-release/chrome/frameworks/GeckiumMaterial/sounds/effects/ogg/Effect_Tick.ogg");`

### Screenshots

n/a

### How do you reproduce the bug/inaccuracy?

1. main

### Expected behaviour or design

not being hardcoded, I guess

**Comment by angelbruni** [comment]
Me when

**Comment by angelbruni** [comment]
Fixed in https://github.com/angelbruni/Geckium/commit/917de70f4bbadc8eedd8050f3c9eb58bc88d03b6
