### ISSUE TITLE
Allow turning off the ticking

### ISSUE THREAD

**Issue by dominichayesferen** [angelbruni/Geckium#359]
### Before sending your suggestion

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Feren OS

### What would you like to suggest for Geckium?

Adding the ticking is fun and all, but I can very much see this being a controversial addition, not only because its exclusivity to GSettings, which doesn't align with Android's "it applies everywhere" principle, and the fact Chrome never had the ticking yet had Material Design pages, but also because it could very easily get on peoples' nerves constantly hearing it.

Thus, if you wanna keep the ticking, give it a shut up option like how phones have vibrate mode (and even a toggle to turn the sound off in general) to turn the sound off, otherwise we won't hear the end of people understandably getting pissed off at the ticking sound.

### Additional Context

- This doesn't exactly make the most sense when it's GSettings only - in Android, the entire UI gets it, not just a single page
- Also doesn't make sense in a Desktop context, admittedly, given... Chrome has Material Design pages but no clicking sound effect.

**Comment by angelbruni** [comment]
Planned

**Comment by angelbruni** [comment]
Added https://github.com/angelbruni/Geckium/commit/78585455314fcb27b346672b42463be8b1d63530, although it's to turn it on not off, the plan was never to have it on by default.
