### ISSUE TITLE
[Regression] Custom Geckium You Color no longer changes nor is previewed on load 

### ISSUE THREAD

**Issue by dominichayesferen** [angelbruni/Geckium#365]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Feren OS

### Summarise the issue

The setting for Custom Geckium You colour (the colour selector) no longer loads the current custom color, nor applies new custom colours.

### Screenshots

i think you can visualise it yourself. 

### How do you reproduce the bug/inaccuracy?

1. Open Geckium Settings while having a custom Geckium You colour
2. See it's black
3. Try changing colour
4. Colour isn't changed in You

### Expected behaviour or design

Colour changed and saved

**Comment by angelbruni** [comment]
Fixed in https://github.com/angelbruni/Geckium/commit/4c13d7569c4af0314ab33ab4262a47afc810dcbd.
