### ISSUE TITLE
2008-2011 Settings Sync Page Layout

### ISSUE THREAD

**Issue by TheMaker69420** [angelbruni/Geckium#374]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox (132.0.2)

### What Operating System are you running Geckium on?

Windows 11 24H2

### Summarise the issue

on any theme before 2012 (Chrome 1 -> 17), the sync page in the settings is messed up. the profile picture is a bit to the right, and the user's name overlaps the profile. this does not happen on themes after 2012 (Chrome 21 -> 58). i have deleted the profile folder and replaced it with the one from the latest update. 

### Screenshots

chrome 1 -> 17 sync page in settings:
![bug](https://github.com/user-attachments/assets/9863e4f5-4a78-4f3b-802d-ced589b20772)

chrome 21 -> 58 sync page in settings:
![2017](https://github.com/user-attachments/assets/8801c138-6b60-4cfb-a0ce-4ae4de894a17)

(email erased from both images for privacy concerns)

### How do you reproduce the bug/inaccuracy?

1: choose any theme from before 2012 (chrome 1 to 17)
2: go to settings 
3: go to the sync page

### Expected behaviour or design

the expected design should be how it looks for the later styles, but in the style of chrome 1 to 17 (ref image below).
![2017](https://github.com/user-attachments/assets/b0ada5a6-66d0-422c-bad8-a72b3ae927b7)

**Comment by angelbruni** [comment]
Fixed in https://github.com/angelbruni/Geckium/commit/1928a7ea3736080622d51a1b0a8c302f37517e56. Thanks.
