### ISSUE TITLE
Searchbar is broken fully impossible to use

### ISSUE THREAD

**Issue by gabeio64** [angelbruni/Geckium#386]
### Before reporting your issue

- [x] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [x] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [ ] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Firefox Developer Edition

### What Operating System are you running Geckium on?

Windows 10 Pro

### Summarise the issue

the searchbar is at the top of the thing not in the little area

### Screenshots

![image](https://github.com/user-attachments/assets/d07fe5e9-707f-4ccd-a9de-3592891b9693)

### How do you reproduce the bug/inaccuracy?

I dont know i just reinstalled my windows 7 theme and this started

### Expected behaviour or design

for it to be in the area its meant to be in

**Comment by angelbruni** [comment]
That's not the only thing that is broken in there.
To me, it just looks like Geckium was not installed properly.
Tab is mising tab texture, buttons are missing icons...
Get it from Releases and try again.
