### ISSUE TITLE
Geckium is showing me gibberish

### ISSUE THREAD

**Issue by KernelTech11** [angelbruni/Geckium#387]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla FireFox

### What Operating System are you running Geckium on?

Windows 11 (Insider Dev)

### Summarise the issue

Geckium is showing me a toggleable option that is just random characters, and i don't know what does it do

### Screenshots

![Captura de tela 2024-12-04 232401](https://github.com/user-attachments/assets/a54b4515-2891-4c6a-85ff-c36cc7194481)

### How do you reproduce the bug/inaccuracy?

1. Download the latest version of Geckium
2. Check Geckium Options

### Expected behaviour or design

This option shouldn't appear

**Comment by dominichayesferen** [comment]
That simply means the string wasn't localised by a translator yet.

Consider forking Geckium, localising the line and submitting a **pull request**.

**Comment by KernelTech11** [comment]
> That simply means the string wasn't localised by a translator yet. ("Click sound feedback", temporarily using pseudolocalisation until Geckium's stable release happens)
> 
> Consider forking Geckium, localising the line and submitting a **pull request**.
ok
