### ISSUE TITLE
account info broken in some versions

### ISSUE THREAD

**Issue by Lukepuke311** [angelbruni/Geckium#388]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

MacOs

### Summarise the issue

in versions from 6 to 25, the account info doesn't change from stock firefox which looks very out of place

### Screenshots

<img width="568" alt="SCR-20241205-tkwy" src="https://github.com/user-attachments/assets/05e0ce30-b290-4218-aec4-596dd48945f6">

### How do you reproduce the bug/inaccuracy?

open geckium and set the theme to any from chrome v6 to v25

### Expected behaviour or design

it should've had a timespan relevant button

**Comment by angelbruni** [comment]
Show me your Geckium Settings in People tab

**Comment by dominichayesferen** [comment]
If your **Avatar Source** is Mozilla Account or was never changed, this is intended - that's your Firefox Account's profile picture, afterall!

To use Chromium's profile pictures, change the Avatar Source.

**Comment by Lukepuke311** [comment]
thanks
