### ISSUE TITLE
Everything being broken

### ISSUE THREAD

**Issue by Thebi499** [angelbruni/Geckium#392]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [ ] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows 11

### Summarise the issue

Everything is broken, also i tested it on Debian (Zorin OS) and windows 7 and both were absolutely broken and tested on specifically Firefox

### Screenshots

https://github.com/user-attachments/assets/245a9c15-058d-4e72-967d-25f5f127dab4

### How do you reproduce the bug/inaccuracy?

Just installing Geckium with Firefox normally

### Expected behaviour or design

What MJD experienced in his video, also when it actually worked for me lool ig

### Additional Context

Also nothing in Geckium settings is functional.

**Comment by angelbruni** [comment]
Get Geckium from Releases https://github.com/angelbruni/Geckium/releases
