### ISSUE TITLE
Geckium doesn't work on Firefox version 133.0.3

### ISSUE THREAD

**Issue by HMA-40** [angelbruni/Geckium#394]
### Before sending your suggestion

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozzilla Firefox

### What Operating System are you running Geckium on?

Windows 11 23H2

### What would you like to suggest for Geckium?

(64 bit version of Firefox btw). Hello guys! 
I'm new here so if I'm doing something wrong, let me know ^w^!
Anyways, I've been having trouble getting Geckium to work on Firefox version 133.0.3. Is there any chance you could help me get it to work? 

Thanks! <:D

**Comment by HMA-40** [comment]
![Screenshot 2024-12-15 124043](https://github.com/user-attachments/assets/d1ecb9fa-bc88-4d17-a838-07c09c1d531c)
Here ya go!

**Comment by angelbruni** [comment]
Thank you!
Could you send a screenshot of your profile folder and `about:support` now, please?

**Comment by HMA-40** [comment]
I'm not sure if this exactly what you want but here you go!
![Screenshot 2024-12-15 124244](https://github.com/user-attachments/assets/32d8ceec-9d30-476d-82b2-a1b2a203f274)

**Comment by dominichayesferen** [comment]
Can you post a screenshot of Mozilla Firefox's EXE's folder?

**Comment by dominichayesferen** [comment]
![360021373-f7f7f0ab-4bd5-495d-8897-e61e07fdaa49](https://github.com/user-attachments/assets/0f920288-72d2-464e-adf2-7fa97779e662)

**Comment by HMA-40** [comment]
Hm, I can not seem to find the .exe folder. I saw it earlier but now I can't find it lol.

**Comment by dominichayesferen** [comment]
see GIF for how to find it

**Comment by HMA-40** [comment]
Yeah, I am looking in that area and all I see is the Mozilla maintenance folders

**Comment by dominichayesferen** [comment]
no firefox.exe?

**Comment by HMA-40** [comment]
Yeah, I literally can not find it

**Comment by dominichayesferen** [comment]
<sup><sub>what</sub></sup>

**Comment by HMA-40** [comment]
Yeh, I downloaded it from their website on Edge as soon as I got this laptop lol.

**Comment by angelbruni** [comment]
Can you send a screenshot of whatever folder comes up if you try through Task Manager?
![image](https://github.com/user-attachments/assets/d401d547-dbf9-498f-ad3f-1e694b937a9d)

**Comment by HMA-40** [comment]
![Screenshot 2024-12-15 125525](https://github.com/user-attachments/assets/e5504069-1e6d-4482-b8fe-f846fe7f7cf9)
Here. I think I found it

**Comment by dominichayesferen** [comment]
now reveal its location.

**Comment by angelbruni** [comment]
Right click and Open File Location like in my screenshot

**Comment by HMA-40** [comment]
Found it.
![Screenshot 2024-12-15 125700](https://github.com/user-attachments/assets/ad326b6c-5d56-46ed-a4ec-c09ff76d6d0a)

**Comment by dominichayesferen** [comment]
you never installed the JS Loader (I called it)

**Comment by HMA-40** [comment]
Ohh, how do I install it then?

**Comment by dominichayesferen** [comment]
follow this GIF

![360021373-f7f7f0ab-4bd5-495d-8897-e61e07fdaa49](https://github.com/user-attachments/assets/e0654ab1-befa-4ef0-8e44-8549cae597e8)

**Comment by dominichayesferen** [comment]
is the Geck working now?

**Comment by HMA-40** [comment]
No. I didn't know I had to have the JS Loader. Btw, where do I find the JS Loader?

**Comment by dominichayesferen** [comment]
In your copy of Geckium - "Firefox Folder"

**Comment by HMA-40** [comment]
Okay, I copied the Firefox Folder into Firefox

**Comment by dominichayesferen** [comment]
restart Firefox
is the Geck working now?

**Comment by angelbruni** [comment]
> Okay, I copied the Firefox Folder into Firefox

Make sure that you copy its contents (the files inside the "Firefox Folder"), not the folder itself

**Comment by HMA-40** [comment]
DUDE. IT WORKED!

**Comment by dominichayesferen** [comment]
Enjoy

**Comment by angelbruni** [comment]
Have fun!

**Comment by HMA-40** [comment]
Thank you so much guys! I appreciate it!
