### ISSUE TITLE
Sorry if this is a question, but does anyone know how to install the latest Firefox ESR on Windows Vista?

### ISSUE THREAD

**Issue by RobRoblox** [angelbruni/Geckium#395]
### Before sending your suggestion

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows Vista Business

### What would you like to suggest for Geckium?

I'm having trouble because I can't watch Facebook videos unless I update to the latest version.

**Comment by KonaloboStudio** [comment]
as far as I know r3dfox works on vista (I use ESR 128.4)

**Comment by Pwnz0rserver2009** [comment]
> I have an extended kernel installed, but I can only install up to version 118.

115 is the only ESR version that supports windows 7 (the version the extended kernel mimics)
essentially, you can't

**Comment by dominichayesferen** [comment]
^ therefore,
