### ISSUE TITLE
New Title Bar style

### ISSUE THREAD

**Issue by SharkGitHubz** [angelbruni/Geckium#397]
### Before sending your suggestion

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows 11 23H2

### What would you like to suggest for Geckium?

So, can you guys make (if possible) a Windows XP title bar? Not changing the font or anything, just the style of it, or maybe a Windows 7 one. Thanks!

**Comment by angelbruni** [comment]
If on 115, you can use Native Controls Patch and disable Compact Borders.
If on a newer version, you can use the fork mentioned in the wiki.

**Comment by dominichayesferen** [comment]
^

As for compact borders:
![image](https://github.com/user-attachments/assets/b734d1e3-73f5-42aa-a8da-68ea191ea1de)
