### ISSUE TITLE
Geckium Apps Not loading

### ISSUE THREAD

**Issue by ikkqqstudio** [angelbruni/Geckium#404]
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Librewolf, yeah i moved to Librewolf a long time ago

### What Operating System are you running Geckium on?

Windows 10 x64 running on PC

### Summarise the issue

Geckium Apps doesn't load at all, it does take a very long time?

### Screenshots

https://mega.nz/file/3FpilQpA#MGmXDOCoq5fiH2d-CXxFNDZUd76Fs_43jo1HlIJhZC4
i linked to the .mkv video file download page because Github doesn't support .mkv files

### How do you reproduce the bug/inaccuracy?

1. I updated to the newest Geckium Update
2. i noticed that all Geckium Apps are not loaded at all in the new update

### Expected behaviour or design

Geckium Apps are not loading at all

**Comment by angelbruni** [comment]
This is a known issue and the changelogs tell you how to fix it.

**Comment by ikkqqstudio** [comment]
okay but why Geckium Apps are loaded with Google Apps?
