### ISSUE TITLE
proper way to install chrome themes

### ISSUE THREAD

**Issue by Pwnz0rserver2009** [angelbruni/Geckium#406]
### Before sending your suggestion

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows 7

### What would you like to suggest for Geckium?

allow a easier way to install themes for google chrome since 1: the chrome webstore doesn't support firefox (..obviously) and 2: the unofficial method of obtaining CRXes (messing with the webstore's download URL) appears to no longer support firefox

**Comment by angelbruni** [comment]
I can confirm that the [userScript](https://github.com/angelbruni/CRX-Downloader-userScript/raw/refs/heads/main/crx-downloader.user.js) present in the README.md still works. It's the easiest way to install themes.
