### ISSUE TITLE
install instructions for Elementary OS

### ISSUE THREAD

**Issue by Pwnz0rserver2009** [angelbruni/Geckium#410]
### Before sending your suggestion

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [ ] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozilla firefox

### What Operating System are you running Geckium on?

Elementary OS

### What would you like to suggest for Geckium?

exactly what the title says since firefox doesn't install to usr/lib/firefox(-ESR) on elementary OS apparently (checked opt too, but there's nothing there)

**Comment by dominichayesferen** [comment]
Follow the Linux instructions relating to Ubuntu.

**Comment by Pwnz0rserver2009** [comment]
> Follow the Linux instructions relating to Ubuntu.

where? everywhere i've looked, there's no ubuntu instructions
and for reasons already said, the generic linux instructions don't work

**Comment by dominichayesferen** [comment]
mb, it's in Compatibility not Instructions. https://github.com/angelbruni/Geckium#compatibility

**Comment by Pwnz0rserver2009** [comment]
slight problem, elementary installs from snap (on apt) even if the ppa is installed
