### ISSUE TITLE
about:apps

### ISSUE THREAD

**Issue by dominichayesferen** [angelbruni/Geckium#96]
That Linux Dude Dominic Hayes thatlinuxdude
 — 10/05/2024 17:48

Starting in 47. It would be a clone of the Chrome 21 NTP that lacks the first page. 

For earlier eras, ig just redirect to the New Tab's apps page.
Could map it to New Tab page preference? (edited)

**Comment by ikkqqstudio** [comment]
oh.
thanks dude for adding this
